### ISSUE TITLE
Customising Menu

### ISSUE THREAD

**Issue by MikeJohnPage** [JohnCoene/fullPage#4]
Any idea how I can customise the menu bar (e.g., font, location, highlights, etc.)? Do I need to edit the css files in the `/inst` directory?

Thanks for making this package, it is really appreciated.

**Comment by JohnCoene** [comment]
You can override the current CSS.

```css
#tocMenu li {
	display:inline-block;
	margin: 10px;
	color: #000;
	background:#fff;
	background: rgba(255,255,255, 0.5);
	-webkit-border-radius: 4px;
            border-radius: 4px;
}
#tocMenu li.active{
	background:#666;
	background: rgba(0,0,0, 0.5);
	color: #fff;
}
#tocMenu li a{
	text-decoration:none;
	color: #000;
}
#tocMenu li.active a:hover{
	color: #000;
}
#tocMenu li:hover{
	background: rgba(255,255,255, 0.8);
}
#tocMenu li a,
#tocMenu li.active a{
	padding: 9px 18px;
	display:block;
}
#tocMenu li.active a{
	color: #fff;
}
#tocMenu{
  text-align: left;
	position:fixed;
	top:0;
	left:0;
	height: 40px;
	z-index: 70;
	width: 100%;
	padding: 0;
	margin:0;
}
.in{
   position: absolute;
   top: 200px;
   left: 0;
   width: 100%;
}
.wrapper{
   position: relative;
   width: 100%; /* for IE 6 */
}
```

In R.

```r
ui <- fullPage(
  tags$head(
    tags$link(href="www/myStyles.css",rel = "stylesheet")
  ),
  menu = c("Full Page" = "link1", "Sections" = "link2"),
  opts = options,
  fullSection(
    center = TRUE,
    menu = "link1",
    tags$h1("fullPage.js meets Shiny")
  ),
  fullSection(
    center = TRUE,
    menu = "link2",
    tags$h1("fullPage.js meets Shiny")
  )
)
```
